---
title: "Stats_Project"
author: "Nathan Gottlieb"
date: "3/7/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(readr)
library(tidyverse)
library(lubridate)
```


```{r}
spdata <- S_P_500_Data %>%
  mutate(name = "sp")
```

```{r}
Russell <- Russel_Index %>%
  mutate(name = "russ")
```

```{r}
tenyr_note <- X10_year_yield
```

```{r}
tenyr_note <-tenyr_note %>% 
  mutate(close = as.numeric(gsub("[\\%,]", "", Close)))
```

```{r}
both <- spdata %>%
  left_join(Russell,
            by = c("Date" = "Date" )) %>%
  mutate(spclose = Close.x )%>%
  mutate(russclose = Close.y) %>%
  select(Date, spclose, russclose) %>%
  pivot_longer(cols = -Date,
               names_to = "Index" ,
             values_to = "Close") 
  
```

```{r}
both %>%
  ggplot(aes(x = mdy(Date), y = Close, color = Index))+
  geom_line() +
  theme_minimal()+
  labs(title = "Large Cap vs Small Cap Data", x = "", y = "", color ="", caption = "The Black line represents COVID Shutdown") + 
  geom_vline(xintercept = ymd("2020-03-09"))
  
```

```{r}
tenyr_note %>%
  ggplot(aes(x= mdy(Date), y = close))+
  geom_line(color = "darkgreen")+
  theme_minimal()+
  labs(title = "Treasury Note Interest Rate", x = "", y = "", color = "") +
  geom_vline(xintercept = ymd("2020-03-09"))
```
```{r}
percent_both<- both %>% 
  mutate(percent = Close/(if_else(Index == "spclose", 3257.85,1666.77))-1)
```

```{r}
percent_both %>% 
  ggplot(aes(x = mdy(Date), y = percent, color = Index)) +
  geom_line() +
  theme_minimal() +
  geom_hline(yintercept = 0.0) +
  geom_point(aes(x = as.Date("2020-12-4"), y = 0.135448225, color = "Where Russ overtook S and P"))
```

```{r}
VGT_JETS <- VGT_Tech_ETF %>%
  left_join(JETS_Airplane_ETF,
            by = c("Date" = "Date" )) %>%
  left_join(AWAY_Travel_ETF, by = c("Date" = "Date")) %>% 
  mutate(Tech = Close.x )%>%
  mutate(Airlines = Close.y) %>%
  mutate(Travel = Close) %>% 
  select(Date, Tech, Airlines, Travel) %>% 
  pivot_longer(cols = -Date,
              names_to = "Index" ,
             values_to = "Close") 
```

```{r}
percent_sectors<- VGT_JETS %>% 
  mutate(percent = Close/(if_else(Index == "Tech", 249.34,if_else(Index == "Airlines", 31.85, 24.82)))-1)
```
```{r}
percent_sectors %>% 
  ggplot(aes(x = mdy(Date), y = percent, color = Index)) +
  geom_line() +
  theme_minimal() +
  geom_vline(xintercept = ymd("2020-03-09"))
```
```{r}
VIX_Volitility_Index %>%
  ggplot(aes(x= mdy(Date), y = Close))+
  geom_line(color = "grey")+
  theme_minimal()+
  labs(title = "VIX Volatility Rate", x = "", y = "", color = "") +
  geom_vline(xintercept = ymd("2020-03-09"))
```

```{r}
VGT_JETS_OCT <- VGT_Tech_ETF_10_1 %>%
  left_join(JETS_Airplane_ETF_10_1,
            by = c("Date" = "Date" )) %>%
  left_join(AWAY_Travel_ETF_10_1, by = c("Date" = "Date")) %>% 
  mutate(Tech = Close.x )%>%
  mutate(Airlines = Close.y) %>%
  mutate(Travel = Close) %>% 
  select(Date, Tech, Airlines, Travel) %>% 
  pivot_longer(cols = -Date,
              names_to = "Index" ,
             values_to = "Close") 
```

```{r}
percent_sectors_OCT<- VGT_JETS_OCT %>% 
  mutate(percent = Close/(if_else(Index == "Tech", 315.33,if_else(Index == "Airlines", 17.12, 19.22)))-1)
```

```{r}
percent_sectors_OCT %>% 
  ggplot(aes(x = mdy(Date), y = percent, color = Index)) +
  geom_line() +
  theme_minimal() 
```


